name: Auto Release Note Generation CI

on:
  release:
    types: [published]

jobs:
  release-note:
    if: startsWith(github.ref, 'refs/tags') && !github.event.release.prerelease
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get last stable release
        uses: rez0n/actions-github-release@v1.7
        id: stable_release_tag
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          type: stable
          repositoty: "Dauflo/github-action-playground"
      - name: Create changelog
        uses: mikepenz/release-changelog-builder-action@v1.4.2
        id: github_release
        with:
          fromTag: ${{ steps.stable_release_tag.outputs.release }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          body: ${{ steps.github_release.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: ${{ github.event.release.prerelease }}
