name: Fix deprecation

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Get commit
        id: commit
        # run: echo ::set-output name=commit_value::$(echo ${GITHUB_SHA})
        run: echo "commit_value=$(echo ${GITHUB_SHA} | tr -d '\n' | jq -R -s -c 'split(\"\")')" >> $GITHUB_OUTPUT

      - name: Check if it worked
        run: echo ${{ steps.commit.outputs.commit_value }}