name: Fix deprecation

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Get commit
        id: commit
        run: echo ::set-output name=commit_value::$(echo ${GITHUB_SHA})

      - name: Check if it worked
        run: echo ${{ steps.commit.outputs.commit_value }}